### ISSUE TITLE
Pac Man GIF stops midway

### ISSUE THREAD

**Issue by ghost** [Ralim/IronOS-Meta#11]
**Describe the Bug**
Other GIF files seem to work but the Pac Man one stops before ending (the frame stays on screen the time set on the duration of logo option).

**To Reproduce**
1. Flash arcade_pac_man.gif.hex
2. Set a duration for the logo
3. Boot

**Details of your device:**
 - Device: TS100
 - Release: v.2.18.70565DE
 - Power adapter being used: 5 V

**Additional context**
Should I lighten up the original GIF or maybe make it last less?

**Comment by Ralim** [comment]
Looking at the build logs, I suspect this is the gif with the warning `Truncating animation after 18 frames as we are out of space`

**Comment by ghost** [comment]
Must find a way to shrink down animations a little bit, the compiler doesn't run on optimized ones.

**Comment by Ralim** [comment]
Not sure what you mean by optimized ones?
This is storing the deltas per stripe (8 vertical pixels). So animations that turn on and off are costly; where as animations that only turn on or off are less costly (half the delta).
The encoding doesn't do fancy encoding; its meant to be quick and easy for the firmware to decode.

**Comment by ghost** [comment]
Right, naively I was already doing this GIF-side getting `ERROR: You have a frame that is different to the first frame time. Mixed rates are not supported`. Thanks.

**Comment by Ralim** [comment]
Yeah it will use the first inter-frame timing for the whole gif, to save having to encode each frames timing. Since most are roughly the same frame timing; saves a few bytes.
