### ISSUE TITLE
Create automatically files for lefties

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS-Meta#15]
@Ralim
Since there is not for every **`.png`** / **`.gif`** a *lefty-version*, it would be nice, if the algorithm creating the corresponding **`.dfu`** & **`.hex`** files would *create* and *name* them *(by attaching **`_L`**)* automatically using the present files.

So there would be less files in the Images folder (all lefty-versions could be deleted) and one would not have to manually convert files into lefty ones. 😊

thanks in advance

**Comment by discip** [comment]
@cybernesto
Good evening Sir,
if I recall correctly you are able to pull this off, would you? 😊

thanks in advance

**Comment by Ralim** [comment]
Apologies for the delay on this; but its now done :)

**Comment by discip** [comment]
## Thank you very much! 😃👍

**Comment by discip** [comment]
@Ralim
Since you already know I am very nitpicky. 😅
Maybe you could change the auto generated format from e.g.:

## *`IronOS.gif_L.dfu`* => `IronOS_L.gif.dfu`
Thanks in advance

**Comment by discip** [comment]
@Ralim
Since you already know I am very nitpicky. 😅
Maybe you could change the auto generated format from e.g.:

## *`IronOS.gif_L.dfu`* => `IronOS_L.gif.dfu`

ps. Unfortunately I was not able to achieve this myself, although I tried.

Thanks in advance

**Comment by discip** [comment]
@Ralim
Since you already know I am very nitpicky. 😅
Maybe you could change the auto generated format from e.g.:

## *`IronOS.gif_L.dfu`* => `IronOS_L.gif.dfu`

ps. Unfortunately I was not able to achieve this myself, although I tried.

Thanks in advance

**Comment by discip** [comment]
## Thanks!😃
