### ISSUE TITLE
Semi legit logos?

### ISSUE THREAD

**Issue by tyeth** [Ralim/IronOS-Meta#16]
Hi, love the project!
I was dreaming of a Lemmings scene, where one would walk on screen and take the blocking stance, before the fast-forward icon appears and lemmings enter from one side of the screen, then the nuclear countdown begins and the scene ends with the pixel explosions of each lemming. Maybe a bit ambitious, and the legality makes me think it wouldn't be well received, or is there some kind of artistic use which would allow such things?

**Comment by Ralim** [comment]
I don't think you would have enough room in storage for an animation like that sadly :(
You are limited to a handful of frames (plan for like 10 frames).
You might be able to do a rather cut down idea of this; and at the low res it would probably not be as recognisable as being a lemmings copy?

**Comment by tyeth** [comment]
Ah yeah, I wondered if the delta frames might just make it possible, I'm a
dreamer... You raise a good point though about recognisability: "That sir
is an exploding stick-person, you can tell by the lack of lemmings
hairstyle. He just happens to like that stretching position very similar in
stance to a "blocker" lemming, case thrown out of court"

**Comment by discip** [comment]
@tyeth
Since this is not realizable, please consider to close this. 😊

thanks in advance
