### ISSUE TITLE
corrupted animation if result is exactly 1024 bytes

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS-Meta#18]
Unfortunately I have encountered another limitation of the *'compile script'*.

If a file fills up the **space** of **1024 byte** exactly, the compiled dfu is corrupted, because there are **2 more frames** at the end of the animation, which consist of **1 entirely white screen** and 1 where only the upper half is white.

Please help.

reference: https://github.com/discip/IronOS-Meta/actions/runs/2766439271

**Comment by discip** [comment]
@Ralim
Good morning Sir,
does a 👍 mean that you are already on it?
And if so, how can I assist?

btw:
Is it possible to log not only the amount of frames, but also the name of the corresponding **`.gif`**?

Thanks in advance

**Comment by Ralim** [comment]
Hia,
The 👍🏼 was meant to be "I've seen this and I'm aware; and ill be back when I have time to poke".Roughly anyway.

I think this is an IronOS bug. Happy to leave ticket here. Will try and get this patched for you shortly.

> Is it possible to log not only the amount of frames, but also the name of the corresponding .gif?
Added this to main for you

**Comment by discip** [comment]
Thanks!
I'll try to be patient. 😊

**Comment by discip** [comment]
@Ralim
I recently found that there was already a similar problem in the past that you were able to solve (https://github.com/Ralim/IronOS-Meta/issues/7), but what could be causing it to appear again?

**Comment by discip** [comment]
## Ooops ... I just realized: I was the one creating this issue when working on the boot logo options! 😅
It is solved now! 😊
