### ISSUE TITLE
Issue flashing IronOS GIF logo

### ISSUE THREAD

**Issue by ricktendo** [Ralim/IronOS-Meta#31]
I tested the latest IronOS.gif.hex Aug release and the bootup animation works fine, but after this is what the screen looks like:

![PXL_20221028_184208493](https://user-images.githubusercontent.com/10519232/198754208-eea5395f-9fce-46c3-bf44-5eabac8a17a4.jpg)

I also tested flashing the IronOS.gif.dfu after upgrading to DFU bootloader v0.2, but this also has the same issue.

I tested previous GIF versions latest PNG version and they work fine.

**Comment by discip** [comment]
@ricktendo
Which IronOS are you running?
Please try any after this [commit](https://github.com/Ralim/IronOS/tree/e43449011ecf08d42ae5639edb4ec8da4e81d030).

**Comment by ricktendo** [comment]
@discip TS100 v2.19 English, the boot logo is the miniware.

**Comment by discip** [comment]
I was referring to the version. 😄
Please try this one [TS100](https://github.com/Ralim/IronOS/suites/9020911410/artifacts/416068651).

**Comment by discip** [comment]
I was referring to the version. 😄
Please try this one [TS100](https://github.com/Ralim/IronOS/suites/9020911410/artifacts/416068651).

**Comment by discip** [comment]
@ricktendo
I was referring to the version. 😄
Please try this one [TS100](https://github.com/Ralim/IronOS/suites/9020911410/artifacts/416068651).

**Comment by ricktendo** [comment]
@discip tested and working, thanks!

**Comment by discip** [comment]
You are welcome!
