### ISSUE TITLE
If created .gif is exactly 1024 bytes it creates artifacts in the last frame

### ISSUE THREAD

**Issue by discip** [Ralim/IronOS-Meta#7]
I have tried to pack up the present space right up to its rim and found out that it compiles without errors, but creates artifacts in the last frame when flashed on the device (**TS80P**).

Here is the file I used (If someone is willing to reproduce the issue.):
![IronOS](https://user-images.githubusercontent.com/53649486/157126878-0966060a-4040-492e-8c7c-9d1065f6c600.gif)

**Comment by Ralim** [comment]
Looking into it tonight if I get time.

**Comment by Ralim** [comment]
That commit ^ Should fix this for you :)
